name: SmartBox Deloitte Sign Workflow

on:
  push:
    branches: [ aws-app-runner ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v3
        
    - name: Docker Build
      run: |
        docker build -t smartbox-deloittesign:${GITHUB_SHA::6} .
        docker tag smartbox-deloittesign:${GITHUB_SHA::6} ghcr.io/smartlawbox/smartbox-deloittesign:${GITHUB_SHA::6}
        docker login ghcr.io -u smartlawbox --password "${{ secrets.PAT_TOKEN }}"
        docker push ghcr.io/smartlawbox/smartbox-deloittesign:${GITHUB_SHA::6}

